### ISSUE TITLE
EdgeObjects: Setting End Param to 1f will result in -0.0001f and weird EdgeObject Behavior

### ISSUE THREAD

**Issue by FritzsHero** [embeddedt/RoadArchitect#4]
**Bugs:**
1. Setting end param: to 1f will result in -0.0001f
2. Setting up 2 EdgeObjects and typing the exact same end param will lead to different results...

**Reproduction:**
1. Create a Road and add EdgeObjects to a Node (Left and Right).
2. Set the Edge-Objects to use the same params (start: 0f and end: 1f(it will swap to -0.0001f as soon as you tap out of the edit field or by dragging the Slider to the maximum value))
3. Set the Distance between Objects to 50m or so.
4. You will mostly discover this Behavior of misplaced EdgeObjects at the End of the Road/Spline.

**Expected behavior:**
Every 50m should appear a EdgeObject, which is placed on the exact opposite Position of the other Object. 

**Screenshots:**
![weird behaviour](https://user-images.githubusercontent.com/10697943/51625671-0db65f80-1f3e-11e9-945d-335508562835.PNG)
![edgeobjects1](https://user-images.githubusercontent.com/10697943/51625672-0db65f80-1f3e-11e9-94d1-25b9e84612b8.PNG)
![edgeobjectstyping1](https://user-images.githubusercontent.com/10697943/51625673-0db65f80-1f3e-11e9-8041-eb6bd8dd4a71.PNG)

**Unity version:**

2018.3 Beta Versions; 2018.3.1f1; 2018.3.2f1

**Comment by embeddedt** [comment]
@FritzsHero I can reproduce both of these issues.

1. I tried to track down what is causing this but the code was not well documented so I couldn't find the issue. As a workaround just use `0.99`, and the logic will automatically round it to the closest supported value.
2. Again, the lack of documentation makes this really hard to fix. Workaround: try altering the start and end params a bit until you find a combination that looks reasonable.

By the way, that road looks great!

**Comment by FritzsHero** [comment]
This Issue should be fixed.
The End Param Bug is located at: Line:796; Script: GSDSplineC (on FritzsHero/RoadArchitect); Function: GetSplineValue
The displacing of EdgeObject is located at: Line: 1200-1252; Script: GSDRoadEdgeObjects (on FritzsHero/RoadArchitect); Function: SetupLocations

However I'm not sure about the SplineMath and to me it looks like when setting up 50m Distance between EdgeObject it will be almost 50m, but not full 50m between each Object....

**Comment by embeddedt** [comment]
@FritzsHero Thanks for doing the investigation and fixing the bug! I'll try your branch when I get a chance.

**Comment by embeddedt** [comment]
@FritzsHero Works as expected now! Thanks!
