### ISSUE TITLE
Online manual links are redirecting

### ISSUE THREAD

**Issue by FritzsHero** [embeddedt/RoadArchitect#6]
I am currently planning on optimizing some stuff in the Code.

It seems that the "online manual" in the code and editor, just links to: http://microgsd.com/Support.aspx
which just redirects to the master branch of RoadArchitect: https://github.com/MicroGSD/RoadArchitect

I do want to hear your opinion about just hard coding the Github Link, replacing the upper one.
Just gets rid of the redirection and therefore a server call, no one needs?
Or is that not a problem, at least for now?

Fritzs

**Comment by embeddedt** [comment]
@FritzsHero At the moment I see no issue with replacing the link. It can always be changed again later if necessary.
